# **`Gettting started with PYTORCH`**

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to a tensor
- Creating tensor

1. scaler

In [ ]:
## Scaler
scaler = torch.tensor(7)
type(scaler)

torch.Tensor

In [ ]:
# ndim shows us the dimension of the tensor
scaler.ndim

0

In [ ]:
# get tensor back as python int
scaler.item()
type(scaler.item())

int

2. vector

In [ ]:
## vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
# shape shows us the what is the height, width or depth
# if the tensor have depth
vector.shape

torch.Size([2])

3. Matrix

In [ ]:
## MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])

In [ ]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0][0]

tensor(7)

4. Tensor

In [ ]:
## TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6]
                        ]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
## shape is printing like (depth, height, witdth)
TENSOR.shape

torch.Size([1, 2, 3])

## `**we write the MATRIX and TENSOR in capital because generally in the python we write of define the  matrix or the tensor as upper(A) or any latter or a name for example   A, M, X etc...**`

### now how can we create the random tensor

Why Random tensor?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`




In [ ]:
# Create a random tensor of shape of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0014, 0.6588, 0.6408, 0.3089],
        [0.7080, 0.0479, 0.3043, 0.4440],
        [0.1272, 0.3964, 0.9005, 0.9999]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
fake_image = torch.rand(size = (1,28,28))
fake_image.shape, fake_image.ndim

(torch.Size([1, 28, 28]), 3)

### Zerosa and Ones tensor

In [ ]:
# create a tensor of all zeros
zero = torch.zeros(size = (3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
answer = torch.zeros(size = (3,4))*torch.rand(size = (3,4))
answer

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
## tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
## datatype of the tensor
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [ ]:
torch.range(0, 10)

<ipython-input-42-cf0dcdb325c8>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
## it might get deprecated in the future so instead of range() we will be use arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# here 1 is starting point and 11 is ending point and 2 is the step_size
one_to_ten = torch.arange(1, 11, 2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [ ]:
## creating tensors like
## we don't want to specify the input size and we want to create the tensor
## then we can use like function to create a tensors for example

ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0])

In [ ]:
ten_zeros.shape, one_to_ten.shape

(torch.Size([5]), torch.Size([5]))

In [ ]:
sample = torch.rand(size = (3,4))
sample

tensor([[0.6401, 0.5797, 0.2972, 0.5900],
        [0.4605, 0.0794, 0.2611, 0.5025],
        [0.9252, 0.9375, 0.4089, 0.1466]])

In [ ]:
# we want to create a tesor which is like to above tensor (sample)
# but we want all as zeros or ones without specify the size of the tensor
# than we can use the {zeros_like, ones_like} function of the torch
all_ones = torch.ones_like(sample)
all_zeros = torch.zeros_like(sample)

In [ ]:
all_ones.shape , all_ones.ndim

(torch.Size([3, 4]), 2)

In [ ]:
all_zeros.shape, all_zeros.ndim

(torch.Size([3, 4]), 2)

In [ ]:
sample.shape, sample.ndim

(torch.Size([3, 4]), 2)

## tensors with different datatypes

In [ ]:
## till now we create the tensors of float32 dtypes
## for exaple
sample.dtype

torch.float32

In [ ]:
# Float_32_tensor
float_32_tensor = torch.tensor([3.0, 4.0, 5.0], dtype = None)
## make a tensor of the data type of int64 (we use torch.int64)
int_64_tensor = torch.tensor([3.0, 4.0, 5.0], dtype = torch.int64)

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
int_64_tensor.dtype

torch.int64

In [ ]:
# we can also create the tensor of the datatype of the int32, int16 etc..
# by using torch.int16 or torch.int32
int_16_tensor =  torch.tensor([3.0, 4.0, 5.0], dtype = torch.int16)
int_32_tensor =  torch.tensor([3.0, 4.0, 9.0], dtype = torch.int32)

In [ ]:
int_16_tensor.dtype , int_32_tensor.dtype

(torch.int16, torch.int32)

In [ ]:
## we also give two more parameters along with dtype (device, requires_grad)
float_32_tensor =  torch.tensor([3.0, 6.0, 9.0],
                                dtype = None, # what datatype is the tensor(e.g. float32, int16, int64)
                                device = None, # What device is your tensor on
                                requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

**Note:**Tensors datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# now we want to conver the float32 tensor to float16 tensor
# we can either use "torch.float16" or we can use "torch.half"
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_16_tensor * float_16_tensor

tensor([ 9., 24., 45.], dtype=torch.float16)

# Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape form a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
## Create a tensors

some_tensor = torch.rand(size = (3,4), dtype = torch.float16, device = "cpu", requires_grad=False)
some_tensor

tensor([[0.2007, 0.8154, 0.6719, 0.8491],
        [0.0547, 0.7373, 0.2256, 0.6299],
        [0.4204, 0.1377, 0.3330, 0.7861]], dtype=torch.float16)

In [ ]:
# Find out details about some tensor(this are tensors attributes)
print(f"Datatype of tensor:{some_tensor.dtype}") # default datatype is float32
print(f"Our tensor is on {some_tensor.device}") # By default it will be on cpu
print(f"Shape of our tensor is {some_tensor.shape}") # here we can also use some_tensor.size() instead of the some_tensor.shape to find the size of the tensor

Datatype of tensor:torch.float16
Our tensor is on cpu
Shape of our tensor is torch.Size([3, 4])


Code example:
```python
print(f"shape of our tensor is {some_tensor.size()}")

```

# Manipulating Tensors (tensor operations)

Tensor operation include:

* `Addition`
* `Subtraction`
* `Multiplication (element-wise)`
* `Division`
* `Matrix multiplication`


In [ ]:
# 1. Addition
tensor = torch.tensor([1, 2, 3], dtype = torch.int32)
tensor + 10 # it will add 10 to all the values of tensor

tensor([11, 12, 13], dtype=torch.int32)

`NOTE`: for Addition we can also use torch.add()

```python
tensor = torch.add(tensor,10)
```

In [ ]:
# 2. Multiplication element wise
tensor * 10 # it will multiply 10 to all the values of tensor

tensor([10, 20, 30], dtype=torch.int32)

`NOTE`: for multiplication we can also use torch.mul()

```python
tensor = torch.mul(tensor,10)
```

In [ ]:
## 3.Subtract
tensor - 10 # it will subtract 10 to all the values of tensor

tensor([-9, -8, -7], dtype=torch.int32)

In [ ]:
## 4. Divison
tensor / 10 # it will divide all the values of tensor by 10

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learing

1. `Element-wise Multiplication`
2. `Matrix Multiplication (dot product)`

There are two main rules that performing matrix multiplication need to satisfy:

1. The **inner dimensions** must match:

* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:

* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 2) @ (2, 3) -> (3, 3)`

In [ ]:
## Element wise multiplication

print(tensor, '*', tensor ,f'Equals to {tensor * tensor}')

tensor([1, 2, 3], dtype=torch.int32) * tensor([1, 2, 3], dtype=torch.int32) Equals to tensor([1, 4, 9], dtype=torch.int32)


In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14, dtype=torch.int32)

## we can also use @ operator for the Matrix Multiplication

```python
tensor @ tensor
```

In [ ]:
## Implementing Matrix Multiplication code by hand
%%time
val = 0
for i in range(len(tensor)):
  val += tensor[i] * tensor[i]
print(val)

tensor(14, dtype=torch.int32)
CPU times: user 1.18 ms, sys: 0 ns, total: 1.18 ms
Wall time: 1.19 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 555 µs, sys: 0 ns, total: 555 µs
Wall time: 405 µs


tensor(14, dtype=torch.int32)

## One of the most common error in deep learning : **Shape Errors**

In [ ]:
## Shapes for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tenson_B) this is the same as torch.matmul(tensor_A, tensor_B) (it's an alias for matmul)
torch.matmul(tensor_A, tensor_B.reshape(2,3))

tensor([[ 29,  28,  32],
        [ 65,  66,  72],
        [101, 104, 112]])

### To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose.**
A Transpose switches the axes or dimensions of a given tensor:

In [ ]:
tensor_A = torch.rand(2, 3)
tensor_B = torch.rand(2, 3)

In [ ]:
# torch.matmul(tensor_A, tensor_B) # This will give us a Shape mismatch or shapes cannot be multiplied error

In [ ]:
tensor_B

tensor([[0.6598, 0.6469, 0.5825],
        [0.7717, 0.7144, 0.7498]])

In [ ]:
tensor_B.T

tensor([[0.6598, 0.7717],
        [0.6469, 0.7144],
        [0.5825, 0.7498]])

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[1.2547, 1.4856],
        [0.8693, 1.0341]])

In [ ]:
# The Matrix Multiplication operation works when tensor_B is Transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([2, 3]), tensor_B = torch.Size([2, 3])
New shapes: tensor_A = torch.Size([2, 3]) (same shape as above), tensor_B.T = torch.Size([3, 2])
Multiplying: torch.Size([2, 3]) @ torch.Size([3, 2]) <- inner dimensions must match
Output:

tensor([[1.2547, 1.4856],
        [0.8693, 1.0341]])

Output shape: torch.Size([2, 2])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.dtype

torch.int64

In [ ]:
# to find min value
print(torch.min(x))
print(x.min())
# we can use either of any one

tensor(1)
tensor(1)


In [ ]:
# to find max value
print(torch.max(x))
print(x.max())
# we can use either of any one

tensor(91)
tensor(91)


In [ ]:
# to find mean value
print(torch.mean(x.type(torch.float32)))
print(x.type(torch.float32).mean())
# we can use either of any one to find mean value of the given tensor
# Note: torch.mean() function  requires a tensor of float32 datatype to work

tensor(46.)
tensor(46.)


In [ ]:
# to find sum of the given tensor we can use
# either
print(torch.sum(x))
# or
print(x.sum())

tensor(460)
tensor(460)


## write a code to find positional min, max of the given tensor

In [ ]:
# we can use argmax or argmin to find positional min, max of the given tensor
print(f"Minimum value is at the index: {torch.argmin(x)} in the given tensor")
print(f"Maximum value is at the index: {torch.argmax(x)} in the given tensor")

Minimum value is at the index: 0 in the given tensor
Maximum value is at the index: 9 in the given tensor


In [ ]:
print(f"we have minimum value {x[torch.argmin(x)]} at the index of {torch.argmin(x)}")
print(f"we have maximum value {x[torch.argmax(x)]} at the index of {torch.argmax(x)}")

we have minimum value 1 at the index of 0
we have maximum value 91 at the index of 9


## Now We will try do Reshaping, stacking, squeezing and unsqueezing of the given tensor

* `Reshaping` - reshape an input tensor to a defined shape

* `View` - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* `Stacking` - combine multiple tensors on top of each other (vstack) or side by side (hstack)

* `Squeeze` - removes all `1` dimensions from a tensor

* `Unsqueeze` - add a `1` dimension to a target tensor

* `Permute` - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Creating a tensor
import torch
tensor_x = torch.arange(1. , 10.)
tensor_x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

### 1. Reshaping

In [ ]:
print(f"Tensor shape is {tensor_x.shape}")

Tensor shape is torch.Size([9])


In [ ]:
# Add an extra dimension(by using Reshape)
tensor_y = tensor_x.reshape(1,9)
tensor_y

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
print(f"Shape of the tensor before Reshaping is : {tensor_x.shape}")
print(f"Shape of the tensor after Reshaping is: {tensor_y.shape}")

Shape of the tensor before Reshaping is : torch.Size([9])
Shape of the tensor after Reshaping is: torch.Size([1, 9])


In [ ]:
# what if i try reshape(3,-1)
tensor_z = tensor_x.reshape(3,-1)
tensor_z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
print(f"Shape of the tensor before Reshaping is : {tensor_x.shape}")
print(f"shape of the tensor after Reshaping(3, -1) is :{tensor_x.reshape(3, -1).shape}")

Shape of the tensor before Reshaping is : torch.Size([9])
shape of the tensor after Reshaping(3, -1) is :torch.Size([3, 3])


### 2. View

In [ ]:
# change the view
tensor_view = tensor_x.view(1,9)
tensor_view

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
### Note : Changing tensor_view changes tensore_x (because a view of a tensor shares the same memory as the original input)
print(f"Tensor before do some changes into tensor_view : {tensor_x}")
tensor_view[:,0] = 5.0
print(f"Tensor after do some changes intp tensor_view : {tensor_x}")

Tensor before do some changes into tensor_view : tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Tensor after do some changes intp tensor_view : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


### 3.Stacking


In [ ]:
# Stack tensors on top of each other
x_stacked_h = torch.stack([tensor_x,tensor_x,tensor_x,tensor_x], dim = 0) # dim = 0 done the horizontal stacking
x_stacked_h

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked_v = torch.stack([tensor_x,tensor_x,tensor_x,tensor_x], dim = 1)
x_stacked_v

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_stacked_h.shape

torch.Size([4, 9])

In [ ]:
x_stacked_v.shape

torch.Size([9, 4])

### 4. Squeeze - Removes all single dimensions from a target tensor

In [1]:
import torch
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [3]:
print(f"shape of the x is : {x.shape}")

shape of the x is : torch.Size([2, 1, 2, 1, 2])


In [4]:
# now lets squeeze the x and see the output
y = torch.squeeze(x)
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [5]:
# if we see the shape of the y
y.shape

torch.Size([2, 2, 2])

In [8]:
# if we apply squeeze on a vector than it will remove all 1 dimension from the tensor
print(f"Shape of a tensor before squeeze: {x.shape}")
print(f"Shape of a tensor after squeeze: {y.shape}")

Shape of a tensor before squeeze: torch.Size([2, 1, 2, 1, 2])
Shape of a tensor after squeeze: torch.Size([2, 2, 2])


In [14]:
# if we want to remove a particular 1 dimension from the tensor than we can provide the which 1 dimension we want to reamove
# for example in x we have (2, 1, 2, 1, 2) dimension and the the layer or dimension is (0, 1, 2, 3, 4) it means we have 1 on dim 1 and 3
z = torch.squeeze(x, 1)
z.shape

torch.Size([2, 2, 1, 2])

In [13]:
z = torch.squeeze(x, 0)
z.shape

torch.Size([2, 1, 2, 1, 2])

### Unsqueeze - adds a single dimension to a target tensor at a specific dim(dimension)

In [16]:
tensor_sample = torch.rand(2,4)
tensor_sample.shape

torch.Size([2, 4])

In [20]:
tensor_sample.unsqueeze(0).shape

torch.Size([1, 2, 4])

In [25]:
print(f"Tensor before unsqeeze : {tensor_sample}")
print(f"Tensor's shaep before unsqueeze : {tensor_sample.shape}")
print(f"Tensor after unsqueeze at a dimension 0 : {tensor_sample.unsqueeze(dim = 0)}")
print(f"Tensor's shape after unsqueeze at dimension 0 : {tensor_sample.unsqueeze(dim = 0).shape}")

Tensor before unsqeeze : tensor([[0.2081, 0.0702, 0.0643, 0.8102],
        [0.6909, 0.9236, 0.4933, 0.0830]])
Tensor's shaep before unsqueeze : torch.Size([2, 4])
Tensor after unsqueeze at a dimension 0 : tensor([[[0.2081, 0.0702, 0.0643, 0.8102],
         [0.6909, 0.9236, 0.4933, 0.0830]]])
Tensor's shape after unsqueeze at dimension 0 : torch.Size([1, 2, 4])


In [26]:
# if we want to add single dimension at dimension 1
tensor_sample.unsqueeze(dim = 1)

tensor([[[0.2081, 0.0702, 0.0643, 0.8102]],

        [[0.6909, 0.9236, 0.4933, 0.0830]]])

In [27]:
tensor_sample.unsqueeze(dim = 1).shape ## This will add a single dimension at dimension 1

torch.Size([2, 1, 4])

In [28]:
sample_tensor = torch.arange(1, 11)
sample_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
sample_tensor.shape

torch.Size([10])

In [31]:
sample_tensor.unsqueeze(dim = 1)

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])

In [33]:
sample_tensor.unsqueeze(dim = 1).shape

torch.Size([10, 1])

### Permute - rearranges the dimensions of a target tensor in a specified order

In [34]:
## we use the permute the rearrange the order of the dimension
torch_permute = torch.rand(size = (5, 2, 3))
torch_permute

tensor([[[0.2106, 0.9095, 0.7577],
         [0.5917, 0.6282, 0.3121]],

        [[0.6181, 0.2377, 0.7981],
         [0.4168, 0.1791, 0.3762]],

        [[0.4262, 0.5676, 0.3742],
         [0.8561, 0.9720, 0.5608]],

        [[0.6901, 0.0373, 0.8111],
         [0.1461, 0.9965, 0.1254]],

        [[0.1943, 0.8633, 0.2926],
         [0.3414, 0.7663, 0.3576]]])

In [35]:
torch_permute.shape

torch.Size([5, 2, 3])

In [36]:
# we want to create the tensor of the shape (2, 3, 5)
torch_permute.permute(1, 2, 0)

tensor([[[0.2106, 0.6181, 0.4262, 0.6901, 0.1943],
         [0.9095, 0.2377, 0.5676, 0.0373, 0.8633],
         [0.7577, 0.7981, 0.3742, 0.8111, 0.2926]],

        [[0.5917, 0.4168, 0.8561, 0.1461, 0.3414],
         [0.6282, 0.1791, 0.9720, 0.9965, 0.7663],
         [0.3121, 0.3762, 0.5608, 0.1254, 0.3576]]])

In [37]:
torch_permute.permute(1, 2, 0).shape

torch.Size([2, 3, 5])

In [38]:
print(f"{torch_permute.shape} This is shape of the tensor before apply permute")
print(f"{torch_permute.permute(1, 2, 0).shape} This is the shape of the tensor after apply permute")

torch.Size([5, 2, 3]) This is shape of the tensor before apply permute
torch.Size([2, 3, 5]) This is the shape of the tensor after apply permute


In [50]:
## permute is also share the original tensor same as view does
## it means if do some changes in pemuted vector than it will be also reflected in original tensor
original_tensor = torch.rand(size = (9,))
original_tensor.unsqueeze(dim = 0).shape
permuted_tensor = original_tensor.unsqueeze(dim = 0).permute(1, 0)
permuted_tensor.shape


torch.Size([9, 1])

In [45]:
original_tensor

tensor([0.2831, 0.6911, 0.2424, 0.6124, 0.5058, 0.2522, 0.2172, 0.3880, 0.7031])

In [46]:
permuted_tensor

tensor([[0.2831],
        [0.6911],
        [0.2424],
        [0.6124],
        [0.5058],
        [0.2522],
        [0.2172],
        [0.3880],
        [0.7031]])

In [47]:
permuted_tensor[0][0] = 5.0

In [48]:
permuted_tensor

tensor([[5.0000],
        [0.6911],
        [0.2424],
        [0.6124],
        [0.5058],
        [0.2522],
        [0.2172],
        [0.3880],
        [0.7031]])

In [49]:
original_tensor

tensor([5.0000, 0.6911, 0.2424, 0.6124, 0.5058, 0.2522, 0.2172, 0.3880, 0.7031])

In [51]:
original_tensor = torch.rand(size = (9,))
print(f"Original tensor before changes:{original_tensor}")
print(f"Permuted tensor before changes: {original_tensor.unsqueeze(dim = 0).permute(1, 0)}")
print("These permuted tensor share a memory with original tensor")
print("\n it mean if we do some changes in permuted tensor than the changes will also reflected in the original tensor also")
print("\n if we change the first value of the permuted tensor to 5 than the it should be change in the original tensor also")
permuted_tensor = original_tensor.unsqueeze(dim = 0).permute(1,0)
permuted_tensor[0][0] = 5
print(f"Permuted tensor after changes: {permuted_tensor}")
print(f"Original tensor after changes: {original_tensor}")

Original tensor before changes:tensor([0.7454, 0.3629, 0.8185, 0.4300, 0.7066, 0.3214, 0.7402, 0.1371, 0.6693])
Permuted tensor before changes: tensor([[0.7454],
        [0.3629],
        [0.8185],
        [0.4300],
        [0.7066],
        [0.3214],
        [0.7402],
        [0.1371],
        [0.6693]])
These permuted tensor share a memory with original tensor

 it mean if we do some changes in permuted tensor than the changes will also reflected in the original tensor also

 if we change the first value of the permuted tensor to 5 than the it should be change in the original tensor also
Permuted tensor after changes: tensor([[5.0000],
        [0.3629],
        [0.8185],
        [0.4300],
        [0.7066],
        [0.3214],
        [0.7402],
        [0.1371],
        [0.6693]])
Original tensor after changes: tensor([5.0000, 0.3629, 0.8185, 0.4300, 0.7066, 0.3214, 0.7402, 0.1371, 0.6693])


## **Selecting data form the tensor with the help of the indexing**

`Indexing with pytourch is similar to indexing with numpy`

In [53]:
import torch
import numpy as np


In [56]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [57]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
x[0][0]

tensor([1, 2, 3])

In [65]:
x[0][0][0]
# it is similar to x[0,0,0]

tensor(1)

In [60]:
x[0,0,0]

tensor(1)

## Pytorch tensors and Numpy

Numpy is a popular scientific Python numerical computnig library.

And because of this, Pytorch has funcionality to interact with it.

* Data in Numpy, want in pytorch tensor -> `torch.from_numpy(ndarray)`

* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`


In [66]:
## Numpy array to Torch tensors

import numpy as np
import torch

array = np.random.rand(3,4)
array

array([[0.05715463, 0.3874662 , 0.9388421 , 0.80698028],
       [0.46384225, 0.1563063 , 0.7752277 , 0.82932196],
       [0.97077847, 0.65066051, 0.60720756, 0.21268411]])

In [74]:
array_to_tensor = torch.from_numpy(array)
array_to_tensor = array_to_tensor.type(torch.float64)

In [82]:
print(f"Type of array is {type(array)}")
print(f"Type of array_to_tensor is {type(array_to_tensor)}")

Type of array is <class 'numpy.ndarray'>
Type of array_to_tensor is <class 'torch.Tensor'>


In [76]:
print(array_to_tensor)

tensor([[0.0572, 0.3875, 0.9388, 0.8070],
        [0.4638, 0.1563, 0.7752, 0.8293],
        [0.9708, 0.6507, 0.6072, 0.2127]], dtype=torch.float64)


In [85]:
# Pytorch tensor to Numpy array

tensor = torch.rand(3,4, dtype=torch.float64)
tensor

tensor([[0.7393, 0.7987, 0.0798, 0.1464],
        [0.8217, 0.7132, 0.0969, 0.0850],
        [0.3608, 0.6473, 0.8561, 0.0523]], dtype=torch.float64)

In [86]:
tensor_to_array = torch.Tensor.numpy(tensor)
tensor_to_array

array([[0.73934466, 0.7987428 , 0.07975711, 0.14641993],
       [0.82165422, 0.71317957, 0.09693322, 0.08503595],
       [0.36082005, 0.64729048, 0.85607963, 0.05234   ]])

In [87]:
print(f"Type of tensor is {type(tensor)}")
print(f"Type of tensor_to_array is {type(tensor_to_array)}")

Type of tensor is <class 'torch.Tensor'>
Type of tensor_to_array is <class 'numpy.ndarray'>


In [88]:
## warning : When coverting form numpy -> pytorch , pytorch reflects numpy's default datatype of float64 unless specified otherwise

## Reproducbility(trying to take random out of random)

> `start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again.....`

To reduce the randomness in neural networks and pytorch comes the concept of a `random seed.`

Essentialy what the random seed does if "flabour" the randomness.







In [108]:
import torch
Tensor_A = torch.rand(3,4)
Tensor_B = torch.rand(3,4)

print(Tensor_A)
print(Tensor_B)
print(Tensor_A == Tensor_B)

tensor([[0.4275, 0.3496, 0.3803, 0.8434],
        [0.8925, 0.1010, 0.2474, 0.4152],
        [0.2245, 0.3636, 0.2307, 0.2952]])
tensor([[0.2026, 0.8476, 0.2399, 0.9552],
        [0.2229, 0.8109, 0.8239, 0.9731],
        [0.5417, 0.4579, 0.9936, 0.6395]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [117]:
## Let's make some random but reproducible tensors
import torch

## set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
Tensor_A = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
Tensor_B = torch.rand(3,4)

print(Tensor_A)
print(Tensor_B)
print(Tensor_A == Tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Runnnig tensors and Pytorch objects on the GPUs (and making faster computation)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardwear + pytorch working behind the scenes to make everything hunky dory(good)

In [1]:
!nvidia-smi

Tue Apr 22 07:42:51 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
# check for gpu using pytorch
import torch
torch.cuda.is_available()

True

In [3]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
torch.cuda.device_count()

1

## putting tensors (and models) on the GPU

The reason we want ourp tensors/models on the GPU is because using a GPU results in faster computations.

In [4]:
import torch
import numpy as np
device = "cuda" if torch.cuda.is_available() else "cpu"

# define a tensor
tensor = torch.tensor([4, 5, 6])
print(tensor, tensor.device) # by default it will on cpu

tensor([4, 5, 6]) cpu


In [3]:
# if we want to run particulat tensor on gpy than we have to pass it through tensor
tensor = torch.tensor([1, 2, 3], device = device , dtype = torch.float32)

print(tensor, tensor.device)

tensor([1., 2., 3.], device='cuda:0') cuda:0


In [5]:
# if we don't want to create a new tensor and we want to run our existed tensor on gpu than
tensor = tensor.to(device)

In [6]:
print(tensor , tensor.device)

tensor([4, 5, 6], device='cuda:0') cuda:0


# so there is two methods to pass an tensor to gpu or create a tensor on gpu
```python
# 1. create a new tensor
tensor = torch.tensor([1, 2, 3], device = "cuda" if troch.cuda.is_available() else "cpu")
print(tensor, tensor.device)

# 2. pass a existing tensor from cpu to gpu
tensor = tensor.to("cuda" if torch.cuda.is_available() else "cpu")
print(tensor, tensor.device)
```

## moving tensor back to the CPU

In [8]:
## If tensor is on GPU, can't transform it to Numpy
tensor_numpy = torch.Tensor.numpy(tensor)

# if we excecute this line than we will get a error
#can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [9]:
# to fix this issue we can set it to the CPU first
tensor_array = tensor.to("cpu")
tensor_array = tensor_array.numpy()
tensor_array

array([4, 5, 6])

## Exercise

1. Create a random tensor with shape `(7,7)`

In [13]:
import torch
import numpy as np

tensor1 = torch.rand(size = (7,7))
tensor1.shape

torch.Size([7, 7])

2. perform a matrix multiplication on the tensor from 1 with another random tensor with shape `(1,7)`

In [14]:
tensor2 = torch.rand(size = (1,7))
tensor2.shape

torch.Size([1, 7])

In [19]:
print(f"Shape of tensor1 is {tensor1.shape}")
print(f"Shape of tensor2 is {tensor2.shape}")
print(f"So the Shape of the output of the matrix multiplication is {torch.matmul(tensor1, tensor2.T).shape}")

print(f"output of the matrix multiplication is {torch.matmul(tensor1, tensor2.T)}")

Shape of tensor1 is torch.Size([7, 7])
Shape of tensor2 is torch.Size([1, 7])
So the Shape of the output of the matrix multiplication is torch.Size([7, 1])
output of the matrix multiplication is tensor([[2.3538],
        [1.9773],
        [2.3135],
        [2.0550],
        [1.5597],
        [2.0286],
        [2.3802]])


3. Set the random seed 0 and do 1 & 2 over again

In [23]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(size = (7,7))
torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(size = (1,7))
print(f"tensor1 : {tensor1}")
print(f"tensor2 : {tensor2}")
print("we have to take transpose of the tensor2 to match the inner dimension of the tensor2 and the outer dimension of tensor1")
print(f"Transoposed tensor2: {tensor2.T}")
print("now each time we will get the same output of the matrix multiplication")
print(f"output of the matrix multiplication is {torch.matmul(tensor1, tensor2.T)}")

tensor1 : tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor2 : tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
we have to take transpose of the tensor2 to match the inner dimension of the tensor2 and the outer dimension of tensor1
Transoposed tensor2: tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])
now each time we will get the same output of the matrix multiplication
output of the matrix multiplication is tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],


In [24]:
tensor1.device

device(type='cpu')

4. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent?

In [34]:
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(size = (7,7), device = "cuda" if torch.cuda.is_available else "cpu")
print(tensor1)
print(f"tensor1 is on {tensor1.device}")
torch.cuda.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(size = (1,7), device = "cuda" if torch.cuda.is_available else "cpu")
print(tensor2)
print(f"tensor2 is on {tensor2.device}")
print("now we will do matrix multiplication")
output = torch.matmul(tensor1, tensor2.T)
print(output)
print(f"shape of the output: {output.shape}")

tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903],
        [0.3394, 0.5451, 0.7312, 0.3864, 0.5959, 0.7578, 0.2126],
        [0.7198, 0.9845, 0.5518, 0.0981, 0.0582, 0.5839, 0.1083],
        [0.9461, 0.3170, 0.8328, 0.6676, 0.2886, 0.9022, 0.8115],
        [0.1784, 0.9534, 0.1486, 0.3882, 0.7977, 0.1752, 0.5777],
        [0.1949, 0.8499, 0.3125, 0.2156, 0.0383, 0.4934, 0.3138],
        [0.3121, 0.5664, 0.1266, 0.7097, 0.0040, 0.5147, 0.2811]],
       device='cuda:0')
tensor1 is on cuda:0
tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903]],
       device='cuda:0')
tensor2 is on cuda:0
now we will do matrix multiplication
tensor([[2.5893],
        [2.1242],
        [1.8872],
        [2.5468],
        [1.7516],
        [1.6445],
        [1.6517]], device='cuda:0')
shape of the output: torch.Size([7, 1])


5. Create a two random tensors of shape `(2,3)` and send them both to the GPU

In [38]:
RANDOM_SEED = 1234
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(size = (2,3))
torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(size = (2,3))
print(f"tensor1 is on {tensor1.device}")
print(f"tensor2 is on {tensor2.device}")
print(tensor1)
print(tensor2)
print("now send both tensors to the GPU")
tensor1 = tensor1.to(device)
tensor2 = tensor2.to(device)
print(f"Now tensor1 is on {tensor1.device}")
print(f"Now tansor2 is on {tensor2.device}")
print(tensor1)
print(tensor2)

cuda
tensor1 is on cpu
tensor2 is on cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
now send both tensors to the GPU
Now tensor1 is on cuda:0
Now tansor2 is on cuda:0
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')


6. Perform a matrix multiplication on the tensors you created in 5

In [41]:
output = torch.matmul(tensor1, tensor2.T)
print(output)
print(f"Shape of the output: {output.shape}")

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')
Shape of the output: torch.Size([2, 2])


7. Find the maximum and minimum values of the output of 6

In [42]:
# To find the max and min we will use `torch.min()` and `torch.max()`
min_value = torch.min(output) # we can also use output.min()
max_value = torch.max(output) # we can also use output.max()
print(f"Minimum value of the output: {min_value}")
print(f"Maximum value of the output: {max_value}")

Minimum value of the output: 0.21611443161964417
Maximum value of the output: 0.628727912902832


8. FInd the Maximum and Minimum index values of the output 6

In [43]:
# to find the index of the min and max value of the output we will use `torch.argmin()` and  `torch.argmax()`
idx_min_value = torch.argmin(output)
idx_max_value = torch.argmax(output)

print(f"Minimum value is on the index: {idx_min_value}")
print(f"Maximum value is on the index: {idx_max_value}")

Minimum value is on the index: 1
Maximum value is on the index: 3


9. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [50]:
# To set the random seed fot the gpu we will use `torch.cuda.manual_seed(RANDOM_SEED)`
RANDOM_SEED = 7
torch.cuda.manual_seed(RANDOM_SEED)
# To crate the random tensor we will use torch.rand()
tensor = torch.rand(size = (1, 1, 1, 10), device = "cuda" if torch.cuda.is_available() else "cpu")
print(tensor)
print(f"Shape of the tensor: {tensor.shape}")
# To remove all `1` dimension we will use torch.squeeze()
squeezed_tensor = torch.squeeze(tensor)
print(squeezed_tensor)
print(f"Shape of the squeezed tensor: {squeezed_tensor.shape}")

tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
           0.6333, 0.5733]]]], device='cuda:0')
Shape of the tensor: torch.Size([1, 1, 1, 10])
tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
        0.5733], device='cuda:0')
Shape of the squeezed tensor: torch.Size([10])


NOTE :- `if we set the random seed using torch.cuda.manual_seed() than this seed is not aplicable for the tensor which is on the cpu so when you use torch.cuda.manual_seed() make sure that your tensor is on gpu`