# **`Gettting started with PYTORCH`**

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to a tensor
- Creating tensor

1. scaler

In [9]:
## Scaler
scaler = torch.tensor(7)
type(scaler)

torch.Tensor

In [7]:
# ndim shows us the dimension of the tensor
scaler.ndim

0

In [11]:
# get tensor back as python int
scaler.item()
type(scaler.item())

int

2. vector

In [13]:
## vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [14]:
vector.ndim

1

In [15]:
# shape shows us the what is the height, width or depth
# if the tensor have depth
vector.shape

torch.Size([2])

3. Matrix

In [16]:
## MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])

In [17]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim

2

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
MATRIX[0][0]

tensor(7)

4. Tensor

In [25]:
## TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6]
                        ]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [26]:
TENSOR.ndim

3

In [27]:
## shape is printing like (depth, height, witdth)
TENSOR.shape

torch.Size([1, 2, 3])

## `**we write the MATRIX and TENSOR in capital because generally in the python we write of define the  matrix or the tensor as upper(A) or any latter or a name for example   A, M, X etc...**`

### now how can we create the random tensor

Why Random tensor?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`




In [29]:
# Create a random tensor of shape of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0014, 0.6588, 0.6408, 0.3089],
        [0.7080, 0.0479, 0.3043, 0.4440],
        [0.1272, 0.3964, 0.9005, 0.9999]])

In [30]:
random_tensor.ndim

2

In [31]:
random_tensor.shape

torch.Size([3, 4])

In [33]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [34]:
fake_image = torch.rand(size = (1,28,28))
fake_image.shape, fake_image.ndim

(torch.Size([1, 28, 28]), 3)

### Zerosa and Ones tensor

In [35]:
# create a tensor of all zeros
zero = torch.zeros(size = (3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
answer = torch.zeros(size = (3,4))*torch.rand(size = (3,4))
answer

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
## tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
## datatype of the tensor
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [42]:
torch.range(0, 10)

<ipython-input-42-cf0dcdb325c8>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [45]:
## it might get deprecated in the future so instead of range() we will be use arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# here 1 is starting point and 11 is ending point and 2 is the step_size
one_to_ten = torch.arange(1, 11, 2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [49]:
## creating tensors like
## we don't want to specify the input size and we want to create the tensor
## then we can use like function to create a tensors for example

ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0])

In [50]:
ten_zeros.shape, one_to_ten.shape

(torch.Size([5]), torch.Size([5]))

In [51]:
sample = torch.rand(size = (3,4))
sample

tensor([[0.6401, 0.5797, 0.2972, 0.5900],
        [0.4605, 0.0794, 0.2611, 0.5025],
        [0.9252, 0.9375, 0.4089, 0.1466]])

In [52]:
# we want to create a tesor which is like to above tensor (sample)
# but we want all as zeros or ones without specify the size of the tensor
# than we can use the {zeros_like, ones_like} function of the torch
all_ones = torch.ones_like(sample)
all_zeros = torch.zeros_like(sample)

In [53]:
all_ones.shape , all_ones.ndim

(torch.Size([3, 4]), 2)

In [54]:
all_zeros.shape, all_zeros.ndim

(torch.Size([3, 4]), 2)

In [55]:
sample.shape, sample.ndim

(torch.Size([3, 4]), 2)

## tensors with different datatypes

In [56]:
## till now we create the tensors of float32 dtypes
## for exaple
sample.dtype

torch.float32

In [75]:
# Float_32_tensor
float_32_tensor = torch.tensor([3.0, 4.0, 5.0], dtype = None)
## make a tensor of the data type of int64 (we use torch.int64)
int_64_tensor = torch.tensor([3.0, 4.0, 5.0], dtype = torch.int64)

In [72]:
float_32_tensor.dtype

torch.float32

In [76]:
int_64_tensor.dtype

torch.int64

In [77]:
# we can also create the tensor of the datatype of the int32, int16 etc..
# by using torch.int16 or torch.int32
int_16_tensor =  torch.tensor([3.0, 4.0, 5.0], dtype = torch.int16)
int_32_tensor =  torch.tensor([3.0, 4.0, 9.0], dtype = torch.int32)

In [78]:
int_16_tensor.dtype , int_32_tensor.dtype

(torch.int16, torch.int32)

In [82]:
## we also give two more parameters along with dtype (device, requires_grad)
float_32_tensor =  torch.tensor([3.0, 6.0, 9.0],
                                dtype = None, # what datatype is the tensor(e.g. float32, int16, int64)
                                device = None, # What device is your tensor on
                                requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

**Note:**Tensors datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [83]:
# now we want to conver the float32 tensor to float16 tensor
# we can either use "torch.float16" or we can use "torch.half"
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [84]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [85]:
int_16_tensor * float_16_tensor

tensor([ 9., 24., 45.], dtype=torch.float16)

# Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape form a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [86]:
## Create a tensors

some_tensor = torch.rand(size = (3,4), dtype = torch.float16, device = "cpu", requires_grad=False)
some_tensor

tensor([[0.2007, 0.8154, 0.6719, 0.8491],
        [0.0547, 0.7373, 0.2256, 0.6299],
        [0.4204, 0.1377, 0.3330, 0.7861]], dtype=torch.float16)

In [93]:
# Find out details about some tensor(this are tensors attributes)
print(f"Datatype of tensor:{some_tensor.dtype}") # default datatype is float32
print(f"Our tensor is on {some_tensor.device}") # By default it will be on cpu
print(f"Shape of our tensor is {some_tensor.shape}") # here we can also use some_tensor.size() instead of the some_tensor.shape to find the size of the tensor

Datatype of tensor:torch.float16
Our tensor is on cpu
Shape of our tensor is torch.Size([3, 4])


Code example:
```python
print(f"shape of our tensor is {some_tensor.size()}")

```

# Manipulating Tensors (tensor operations)

Tensor operation include:

* `Addition`
* `Subtraction`
* `Multiplication (element-wise)`
* `Division`
* `Matrix multiplication`


In [95]:
# 1. Addition
tensor = torch.tensor([1, 2, 3], dtype = torch.int32)
tensor + 10 # it will add 10 to all the values of tensor

tensor([11, 12, 13], dtype=torch.int32)

`NOTE`: for Addition we can also use torch.add()

```python
tensor = torch.add(tensor,10)
```

In [100]:
# 2. Multiplication element wise
tensor * 10 # it will multiply 10 to all the values of tensor

tensor([10, 20, 30], dtype=torch.int32)

`NOTE`: for multiplication we can also use torch.mul()

```python
tensor = torch.mul(tensor,10)
```

In [98]:
## 3.Subtract
tensor - 10 # it will subtract 10 to all the values of tensor

tensor([-9, -8, -7], dtype=torch.int32)

In [99]:
## 4. Divison
tensor / 10 # it will divide all the values of tensor by 10

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learing

1. `Element-wise Multiplication`
2. `Matrix Multiplication (dot product)`

There are two main rules that performing matrix multiplication need to satisfy:

1. The **inner dimensions** must match:

* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:

* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 2) @ (2, 3) -> (3, 3)`

In [105]:
## Element wise multiplication

print(tensor, '*', tensor ,f'Equals to {tensor * tensor}')

tensor([1, 2, 3], dtype=torch.int32) * tensor([1, 2, 3], dtype=torch.int32) Equals to tensor([1, 4, 9], dtype=torch.int32)


In [120]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14, dtype=torch.int32)

## we can also use @ operator for the Matrix Multiplication

```python
tensor @ tensor
```

In [109]:
## Implementing Matrix Multiplication code by hand
%%time
val = 0
for i in range(len(tensor)):
  val += tensor[i] * tensor[i]
print(val)

tensor(14, dtype=torch.int32)
CPU times: user 1.18 ms, sys: 0 ns, total: 1.18 ms
Wall time: 1.19 ms


In [114]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 555 µs, sys: 0 ns, total: 555 µs
Wall time: 405 µs


tensor(14, dtype=torch.int32)

## One of the most common error in deep learning : **Shape Errors**

In [123]:
## Shapes for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tenson_B) this is the same as torch.matmul(tensor_A, tensor_B) (it's an alias for matmul)
torch.matmul(tensor_A, tensor_B.reshape(2,3))

tensor([[ 29,  28,  32],
        [ 65,  66,  72],
        [101, 104, 112]])

### To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose.**
A Transpose switches the axes or dimensions of a given tensor:

In [125]:
tensor_A = torch.rand(2, 3)
tensor_B = torch.rand(2, 3)

In [130]:
# torch.matmul(tensor_A, tensor_B) # This will give us a Shape mismatch or shapes cannot be multiplied error

In [127]:
tensor_B

tensor([[0.6598, 0.6469, 0.5825],
        [0.7717, 0.7144, 0.7498]])

In [128]:
tensor_B.T

tensor([[0.6598, 0.7717],
        [0.6469, 0.7144],
        [0.5825, 0.7498]])

In [129]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[1.2547, 1.4856],
        [0.8693, 1.0341]])

In [133]:
# The Matrix Multiplication operation works when tensor_B is Transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([2, 3]), tensor_B = torch.Size([2, 3])
New shapes: tensor_A = torch.Size([2, 3]) (same shape as above), tensor_B.T = torch.Size([3, 2])
Multiplying: torch.Size([2, 3]) @ torch.Size([3, 2]) <- inner dimensions must match
Output:

tensor([[1.2547, 1.4856],
        [0.8693, 1.0341]])

Output shape: torch.Size([2, 2])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [134]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [135]:
x.dtype

torch.int64

In [136]:
# to find min value
print(torch.min(x))
print(x.min())
# we can use either of any one

tensor(1)
tensor(1)


In [137]:
# to find max value
print(torch.max(x))
print(x.max())
# we can use either of any one

tensor(91)
tensor(91)


In [138]:
# to find mean value
print(torch.mean(x.type(torch.float32)))
print(x.type(torch.float32).mean())
# we can use either of any one to find mean value of the given tensor
# Note: torch.mean() function  requires a tensor of float32 datatype to work

tensor(46.)
tensor(46.)


In [139]:
# to find sum of the given tensor we can use
# either
print(torch.sum(x))
# or
print(x.sum())

tensor(460)
tensor(460)


## write a code to find positional min, max of the given tensor

In [145]:
# we can use argmax or argmin to find positional min, max of the given tensor
print(f"Minimum value is at the index: {torch.argmin(x)} in the given tensor")
print(f"Maximum value is at the index: {torch.argmax(x)} in the given tensor")

Minimum value is at the index: 0 in the given tensor
Maximum value is at the index: 9 in the given tensor


In [146]:
print(f"we have minimum value {x[torch.argmin(x)]} at the index of {torch.argmin(x)}")
print(f"we have maximum value {x[torch.argmax(x)]} at the index of {torch.argmax(x)}")

we have minimum value 1 at the index of 0
we have maximum value 91 at the index of 9


## Now We will try do Reshaping, stacking, squeezing and unsqueezing of the given tensor

* `Reshaping` - reshape an input tensor to a defined shape

* `View` - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* `Stacking` - combine multiple tensors on top of each other (vstack) or side by side (hstack)

* `Squeeze` - removes all `1` dimensions from a tensor

* `Unsqueeze` - add a `1` dimension to a target tensor

* `Permute` - Return a view of the input with dimensions permuted (swapped) in a certain way

In [147]:
# Creating a tensor
import torch
tensor_x = torch.arange(1. , 10.)
tensor_x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

### 1. Reshaping

In [148]:
print(f"Tensor shape is {tensor_x.shape}")

Tensor shape is torch.Size([9])


In [149]:
# Add an extra dimension(by using Reshape)
tensor_y = tensor_x.reshape(1,9)
tensor_y

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [150]:
print(f"Shape of the tensor before Reshaping is : {tensor_x.shape}")
print(f"Shape of the tensor after Reshaping is: {tensor_y.shape}")

Shape of the tensor before Reshaping is : torch.Size([9])
Shape of the tensor after Reshaping is: torch.Size([1, 9])


In [152]:
# what if i try reshape(3,-1)
tensor_z = tensor_x.reshape(3,-1)
tensor_z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [153]:
print(f"Shape of the tensor before Reshaping is : {tensor_x.shape}")
print(f"shape of the tensor after Reshaping(3, -1) is :{tensor_x.reshape(3, -1).shape}")

Shape of the tensor before Reshaping is : torch.Size([9])
shape of the tensor after Reshaping(3, -1) is :torch.Size([3, 3])


### 2. View

In [154]:
# change the view
tensor_view = tensor_x.view(1,9)
tensor_view

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [158]:
### Note : Changing tensor_view changes tensore_x (because a view of a tensor shares the same memory as the original input)
print(f"Tensor before do some changes into tensor_view : {tensor_x}")
tensor_view[:,0] = 5.0
print(f"Tensor after do some changes intp tensor_view : {tensor_x}")

Tensor before do some changes into tensor_view : tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Tensor after do some changes intp tensor_view : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


### 3.Stacking


In [162]:
# Stack tensors on top of each other
x_stacked_h = torch.stack([tensor_x,tensor_x,tensor_x,tensor_x], dim = 0) # dim = 0 done the horizontal stacking
x_stacked_h

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [163]:
x_stacked_v = torch.stack([tensor_x,tensor_x,tensor_x,tensor_x], dim = 1)
x_stacked_v

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [164]:
x_stacked_h.shape

torch.Size([4, 9])

In [165]:
x_stacked_v.shape

torch.Size([9, 4])

### 4. Squeeze - Removes all single dimensions from a target tensor